# Generated by Django 5.2.1 on 2025-05-30 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dicom_ae_title',
            field=models.CharField(blank=True, help_text='DICOM AE Title for this user when issuing WADO/STOW calls', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.institution'),
        ),
    ]
